// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minisplitwise.Infrastructure.Data;

#nullable disable

namespace MiniSplitwise.Infrastructure.Migrations
{
    [DbContext(typeof(MinisplitwiseDbContext))]
    [Migration("20260712124406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("Minisplitwise.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("ForEveryone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("for_everyone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<Guid>("PaidById")
                        .HasColumnType("TEXT")
                        .HasColumnName("paid_by_id");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_expenses_group_id");

                    b.HasIndex("PaidById")
                        .HasDatabaseName("ix_expenses_paid_by_id");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("Minisplitwise.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Minisplitwise.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<Guid?>("ExpenseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("expense_id");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("ix_members_expense_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_members_group_id");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Minisplitwise.Domain.Entities.Expense", b =>
                {
                    b.HasOne("Minisplitwise.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_groups_group_id");

                    b.HasOne("Minisplitwise.Domain.Entities.Member", "PaidBy")
                        .WithMany()
                        .HasForeignKey("PaidById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_members_paid_by_id");

                    b.Navigation("Group");

                    b.Navigation("PaidBy");
                });

            modelBuilder.Entity("Minisplitwise.Domain.Entities.Member", b =>
                {
                    b.HasOne("Minisplitwise.Domain.Entities.Expense", null)
                        .WithMany("SharedWith")
                        .HasForeignKey("ExpenseId")
                        .HasConstraintName("fk_members_expenses_expense_id");

                    b.HasOne("Minisplitwise.Domain.Entities.Group", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("fk_members_groups_group_id");
                });

            modelBuilder.Entity("Minisplitwise.Domain.Entities.Expense", b =>
                {
                    b.Navigation("SharedWith");
                });

            modelBuilder.Entity("Minisplitwise.Domain.Entities.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
